#!/bin/bash

VERSION="1.0"
TRASH_PATH="$HOME/.deleted/trash"
BIN_PATH="$HOME/.local/bin"

DO_INSTALL=0

# Update PATH in the appropriate shell configuration file
if [ "$SHELL" = "/bin/bash" ]; then
	echo "Recognized shell: Bash"
	echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> "$HOME/.bashrc"
	DO_INSTALL=1
elif [ "$SHELL" = "/bin/zsh" ]; then
	echo "Recognized shell: ZSH"
	echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> "$HOME/.zshrc"
	DO_INSTALL=1
else
	echo "Unrecognized shell: $SHELL"
fi

if [ $DO_INSTALL -eq 1 ]; then
	# Create necessary directories
	mkdir -p $TRASH_PATH
	mkdir -p $BIN_PATH

	# Copy the scripts and set permissions
	cp ./bin/rm "$HOME/.local/bin/"
	chmod +x "$HOME/.local/bin/rm"
	cp ./bin/del "$HOME/.local/bin/"
	chmod +x "$HOME/.local/bin/del"
	cp ./bin/undel "$HOME/.local/bin/"
	chmod +x "$HOME/.local/bin/undel"
	
	echo "Successfully installed \"del\" and \"undel\" commands, version $VERSION. Please restart your terminal."
fi

